repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-ast
      - id: check-docstring-first
      - id: pretty-format-json
        args: [--autofix, --indent=2, --no-ensure-ascii, --no-sort-keys]
      - id: check-added-large-files
        args: [--maxkb=50000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: name-tests-test
        exclude: ^tests/load/locustfile\.py$
  - repo: https://github.com/google/yamlfmt
    rev: v0.19.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        # codespell 실행을 위해 필요한 의존성을 명시합니다.

        additional_dependencies:
          - codespell
          - tomli # pyproject.toml 파일을 읽기 위해 필요합니다.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.10"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        # pyproject.toml의 설정을 기반으로 문서화율 검사

        args: [-vv, --style=google]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.12.5", "types-requests"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: uv.lock
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv-lock-check
        entry: uv lock --check
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false
