repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        # Verifies that JSON files are valid.
      - id: pretty-format-json
        # Format JSON files.

        args: [--autofix, --indent=2, --no-ensure-ascii, --no-sort-keys]
      - id: check-added-large-files
        # Prevent giant files from being committed.

        args: [--maxkb=500000]
      - id: check-case-conflict
        # Check for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict
        # Check for files that contain merge conflict strings.
      - id: check-yaml
        # Verifies that YAML files are valid.
      - id: check-toml
        # Verifies that TOML files are valid.
      - id: end-of-file-fixer
        # Ensures that a file is either empty, or ends with one newline.
      - id: mixed-line-ending
        # Replaces or checks mixed line ending.
      - id: trailing-whitespace
        # Trims trailing whitespace.

        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
        # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: name-tests-test
        # Verify that test files are named correctly.

        exclude: ^tests/load/locustfile\.py$
      - id: requirements-txt-fixer
        # Sorts entries in requirements.txt.
  - repo: https://github.com/google/yamlfmt
    rev: v0.19.0
    hooks:
      - id: yamlfmt
        # Format YAML files.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        # Check for common misspellings in text files.

        additional_dependencies:
          - tomli
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # An extremely fast Python linter and code formatter, written in Rust.

    rev: "v0.14.10"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      - id: ruff-format
        # Run the formatter.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1 # 최신 버전 확인 권장
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.12.5", # Pydantic 타입 인식을 위해 필요
          "types-requests", # 사용하는 라이브러리의 stub 패키지 추가
        ]
        # pyproject.toml의 설정을 따르도록 구성
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: uv.lock # 제외할 파일 설정
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv-lock-check
        entry: uv lock --check
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false
